


datasets = ['A', 'B']

rule all:
    input:
        expand('lok{d}.txt', d=datasets)

for k in range(2):
    rule :
        name: "makefiles"
        output:
            lok=f'lok{{d}}.txt',
            
        script:
            'makefiles.py'
